<html><head>
    <link href="index.css" rel="stylesheet">
  
  </head><body>
    <div id="mocha"><ul id="mocha-stats"><li class="progress"><canvas width="40" height="40"></canvas></li><li class="passes"><a href="javascript:void(0);">passes:</a> <em>11</em></li><li class="failures"><a href="javascript:void(0);">failures:</a> <em>6</em></li><li class="duration">duration: <em>511.35</em>s</li></ul><ul id="mocha-report"><li class="test pass slow"><h2>httpception<span class="duration">78048ms</span> <a href="blank?grep=httpception" class="replay">‣</a></h2><pre style="display: none;"><code></code></pre></li><li class="test fail"><h2>uninspected (pretest) <a href="blank?grep=uninspected" class="replay">‣</a></h2><pre class="error">Error: Test Failure

&gt; uninspected@2.0.0 test /tmp/fugl/builds/git-github-com-unexpectedjs-uninspected-git
&gt; mocha



  uninspected
    ✓ should be a shorthand for uninspected.log
    #inspect
      1) should produce colored output
      ✓ should have a default depth of 6
    #log
      ✓ should log to the console
      ✓ should log with colors if told to
      ✓ should log without colors if told to
    #diff
      ✓ should log without colors if told to
      ✓ should do something reasonable when diffing primitive values with no specific built-in diff


  7 passing (67ms)
  1 failing

  1) uninspected
       #inspect
         should produce colored output:
     UnexpectedError: 
expected '{ foo: \'abc\' }'
to equal '{ \x1b[90m\x1b[38;5;242mfoo\x1b[39m: \x1b[36m\'abc\'\x1b[39m }'

-{ foo: 'abc' }
+{ \x1B[90m\x1B[38;5;242mfoo\x1B[39m: \x1B[36m'abc'\x1B[39m }

      at Context.it (test/uninspected.js:16:7)
      set UNEXPECTED_FULL_TRACE=true to see the full stack trace




    at createError (/home/travis/build/alexjeffburke/unexpected-build-canary/node_modules/fugl/src/run-in-folder.js:17:10)
    at ChildProcess.npm.on.code (/home/travis/build/alexjeffburke/unexpected-build-canary/node_modules/fugl/src/run-in-folder.js:58:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)</pre><pre style="display: none;"><code></code></pre></li><li class="test fail"><h2>swirl <a href="blank?grep=swirl" class="replay">‣</a></h2><pre class="error">Error: Test Failure

&gt; swirl@3.0.0 test /tmp/fugl/builds/git-github-com-papandreou-swirl-git
&gt; mocha &amp;&amp; npm run lint



  swirl
    1) should produce some output


  0 passing (237ms)
  1 failing

  1) swirl should produce some output:
     
expected Socket
to yield output satisfying when decoded as 'utf-8' to satisfy /HTTP\/1\.1 .*\/\/ should be 412 Precondition Failed/
  expected Buffer([])
  when decoded as 'utf-8' to satisfy /HTTP\/1\.1 .*\/\/ should be 412 Precondition Failed/

     at Array.forEach (&lt;anonymous&gt;)
  From previous event:
      at Context.&lt;anonymous&gt; (test/swirl.js:30:13)
      set UNEXPECTED_FULL_TRACE=true to see the full stack trace




    at createError (/home/travis/build/alexjeffburke/unexpected-build-canary/node_modules/fugl/src/run-in-folder.js:17:10)
    at ChildProcess.npm.on.code (/home/travis/build/alexjeffburke/unexpected-build-canary/node_modules/fugl/src/run-in-folder.js:58:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)</pre><pre style="display: none;"><code></code></pre></li><li class="test fail"><h2>orc-scripts (pretest) <a href="blank?grep=orc-scripts" class="replay">‣</a></h2><pre class="error">Error: Test Failure

&gt; orc-scripts@0.6.5 test /tmp/fugl/builds/https-github-com-orckestra-orc-scripts-git
&gt; node src test


    at createError (/home/travis/build/alexjeffburke/unexpected-build-canary/node_modules/fugl/src/run-in-folder.js:17:10)
    at ChildProcess.npm.on.code (/home/travis/build/alexjeffburke/unexpected-build-canary/node_modules/fugl/src/run-in-folder.js:58:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)</pre><pre style="display: none;"><code></code></pre></li><li class="test pass slow"><h2>mockrequest<span class="duration">8373ms</span> <a href="blank?grep=mockrequest" class="replay">‣</a></h2><pre style="display: none;"><code></code></pre></li><li class="test pass slow"><h2>samlogin<span class="duration">32678ms</span> <a href="blank?grep=samlogin" class="replay">‣</a></h2><pre style="display: none;"><code></code></pre></li><li class="test fail"><h2>test-them-all (pretest) <a href="blank?grep=test-them-all" class="replay">‣</a></h2><pre class="error">Error: Test Failure

&gt; test-them-all@3.0.0 test /tmp/fugl/builds/https-github-com-yormi-test-them-all-git
&gt; NODE_ENV=dev mocha $(find test -name '*_spec.js') --compilers js:babel-core/register -r babel-polyfill -r src/setup/setup --recursive -w


    at createError (/home/travis/build/alexjeffburke/unexpected-build-canary/node_modules/fugl/src/run-in-folder.js:17:10)
    at ChildProcess.npm.on.code (/home/travis/build/alexjeffburke/unexpected-build-canary/node_modules/fugl/src/run-in-folder.js:58:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)</pre><pre style="display: none;"><code></code></pre></li><li class="test pass slow"><h2>yify-query<span class="duration">7995ms</span> <a href="blank?grep=yify-query" class="replay">‣</a></h2><pre style="display: none;"><code></code></pre></li><li class="test pass slow"><h2>eslint-markdown-test<span class="duration">16051ms</span> <a href="blank?grep=eslint-markdown-test" class="replay">‣</a></h2><pre style="display: none;"><code></code></pre></li><li class="test pass slow"><h2>ybdb<span class="duration">22326ms</span> <a href="blank?grep=ybdb" class="replay">‣</a></h2><pre style="display: none;"><code></code></pre></li><li class="test fail"><h2>expect-react-shallow (pretest) <a href="blank?grep=expect-react-shallow" class="replay">‣</a></h2><pre class="error">Error: Test Failure

&gt; expect-react-shallow@1.2.1 test /tmp/fugl/builds/https-github-com-sapegin-expect-react-shallow-git
&gt; npm run lint &amp;&amp; npm run mocha


&gt; expect-react-shallow@1.2.1 lint /tmp/fugl/builds/https-github-com-sapegin-expect-react-shallow-git
&gt; eslint lib


&gt; expect-react-shallow@1.2.1 mocha /tmp/fugl/builds/https-github-com-sapegin-expect-react-shallow-git
&gt; mocha test


    at createError (/home/travis/build/alexjeffburke/unexpected-build-canary/node_modules/fugl/src/run-in-folder.js:17:10)
    at ChildProcess.npm.on.code (/home/travis/build/alexjeffburke/unexpected-build-canary/node_modules/fugl/src/run-in-folder.js:58:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)</pre><pre style="display: none;"><code></code></pre></li><li class="test fail"><h2>assert-the-unexpected <a href="blank?grep=assert-the-unexpected" class="replay">‣</a></h2><pre class="error">Error: Test Failure

&gt; assert-the-unexpected@1.0.0 test /tmp/fugl/builds/git-github-com-alexjeffburke-assert-the-unexpected-git
&gt; mocha



  assertTheUnexpected
    deepEqual
      ✓ should compare objects with loosely equal property (lhs)
      ✓ should compare objects with loosely equal property (rhs)
      ✓ should compare objects with loosely equal array (lhs)
      ✓ should compare objects with loosely equal array (rhs)
      ✓ should compare date and array
      ✓ should compare date and object
      ✓ should loosely compare deep objects
      1) should respect a user supplied message
    doesNotThrow
      ✓ should throw on an unwanted exception
      ✓ should throw and include user defined message
      ✓ should throw the original error on regex mismatch
      ✓ should respect a user defined message on regex mismatch
      ✓ should&nbsp;throw&nbsp;an&nbsp;assertion&nbsp;error&nbsp;on&nbsp;Error&nbsp;type&nbsp;match
      ✓ should&nbsp;throw&nbsp;the&nbsp;original&nbsp;error&nbsp;on&nbsp;Error&nbsp;type&nbsp;mismatch
      ✓ should&nbsp;throw&nbsp;an&nbsp;assertion&nbsp;error&nbsp;on&nbsp;Error&nbsp;type&nbsp;match
    equal
      ✓ should compare 0 and "0"
      ✓ should compare 0 and false
      ✓ should compare 1 and true
      ✓ should compare null with itself
      2) should respect a user supplied message
    ifError
      ✓ should pass on no error
      ✓ should throw on an error
      ✓ should ignore a user supplied message
    notEqual
      ✓ should throw on matching number and string comparison
      3) should respect a user supplied message
    notDeepEqual
      4) should respect a user supplied message
    notDeepStrictEqual
      5) should respect a user supplied message
    notStrictEqual
      6) should respect a user supplied message
    ok
      ✓ should throw on falsy value
      7) should respect a user supplied message
    strictEqual
      8) should respect a user supplied message
    throws
      9) should pass on seeing an exception
      ✓ should throw on a missing exception
      ✓ should throw and include user defined message
      ✓ should throw on a missing exception and regex
      ✓ should&nbsp;throw on missing exception with regex and message
      ✓ should throw the original error on regex mismatch
      ✓ should ignore a user supplied message on regex mismatch
    when used a plain function
      ✓ should throw the
      10) should respect a user supplied message

  node
    - should pass node 4.7.3 tests
    - should pass node 6.15.1 tests


  30 passing (176ms)
  2 pending
  10 failing

  1) assertTheUnexpected deepEqual should respect a user supplied message:
     
expected
function () {
  assert.deepEqual([0], [true], theMessage);
}
to error
function (e) {
  hasAssertionErrorMessage(e, theMessage);
}
  expected
  AssertionError [ERR_ASSERTION]({
    message: 'oh dear', generatedMessage: false, code: 'ERR_ASSERTION',
    actual: undefined, expected: undefined, operator: undefined
  })
  to satisfy
  function (e) {
    hasAssertionErrorMessage(e, theMessage);
  }

  UnexpectedError: 
  expected [ 0 ] to loosely equal [ true ]
  
  [
    false // should equal true
  ]
  
      at wrappedExpect (lib/assertTheUnexpected.js:109:28)
      at Function.deepEqual (lib/assertTheUnexpected.js:389:7)
      at test/assertTheUnexpected.js:87:16
      at Context.&lt;anonymous&gt; (test/assertTheUnexpected.js:86:7)
      set UNEXPECTED_FULL_TRACE=true to see the full stack trace

  2) assertTheUnexpected equal should respect a user supplied message:
     
expected
function () {
  assert.equal('a', 'b', theMessage);
}
to error
function (e) {
  hasAssertionErrorMessage(e, theMessage);
}
  expected
  AssertionError [ERR_ASSERTION]({
    message: 'oh dear', generatedMessage: false, code: 'ERR_ASSERTION',
    actual: undefined, expected: undefined, operator: undefined
  })
  to satisfy
  function (e) {
    hasAssertionErrorMessage(e, theMessage);
  }

  UnexpectedError: 
  expected 'a' to loosely be 'b'
  
  -a
  +b
  
      at wrappedExpect (lib/assertTheUnexpected.js:109:28)
      at Function.equal (lib/assertTheUnexpected.js:420:7)
      at test/assertTheUnexpected.js:173:16
      at Context.&lt;anonymous&gt; (test/assertTheUnexpected.js:172:7)
      set UNEXPECTED_FULL_TRACE=true to see the full stack trace

  3) assertTheUnexpected notEqual should respect a user supplied message:
     
expected
function () {
  assert.notEqual(0, '0', theMessage);
}
to error
function (e) {
  hasAssertionErrorMessage(e, theMessage);
}
  expected
  AssertionError [ERR_ASSERTION]({
    message: 'oh dear', generatedMessage: false, code: 'ERR_ASSERTION',
    actual: undefined, expected: undefined, operator: undefined
  })
  to satisfy
  function (e) {
    hasAssertionErrorMessage(e, theMessage);
  }

  UnexpectedError: 
  expected 0 not to loosely be '0'
  
      at wrappedExpect (lib/assertTheUnexpected.js:109:28)
      at Function.notEqual (lib/assertTheUnexpected.js:428:7)
      at test/assertTheUnexpected.js:216:16
      at Context.&lt;anonymous&gt; (test/assertTheUnexpected.js:215:7)
      set UNEXPECTED_FULL_TRACE=true to see the full stack trace

  4) assertTheUnexpected notDeepEqual should respect a user supplied message:
     
expected
function () {
  assert.notDeepEqual([0], ['0'], theMessage);
}
to error
function (e) {
  hasAssertionErrorMessage(e, theMessage);
}
  expected
  AssertionError [ERR_ASSERTION]({
    message: 'oh dear', generatedMessage: false, code: 'ERR_ASSERTION',
    actual: undefined, expected: undefined, operator: undefined
  })
  to satisfy
  function (e) {
    hasAssertionErrorMessage(e, theMessage);
  }

  UnexpectedError: 
  expected [ 0 ] not to loosely equal [ '0' ]
  
      at wrappedExpect (lib/assertTheUnexpected.js:109:28)
      at Function.notDeepEqual (lib/assertTheUnexpected.js:433:7)
      at test/assertTheUnexpected.js:228:16
      at Context.&lt;anonymous&gt; (test/assertTheUnexpected.js:227:7)
      set UNEXPECTED_FULL_TRACE=true to see the full stack trace

  5) assertTheUnexpected notDeepStrictEqual should respect a user supplied message:
     
expected
function () {
  assert.notDeepStrictEqual([0], [0], theMessage);
}
to error
function (e) {
  hasAssertionErrorMessage(e, theMessage);
}
  expected
  AssertionError [ERR_ASSERTION]({
    message: 'oh dear', generatedMessage: false, code: 'ERR_ASSERTION',
    actual: undefined, expected: undefined, operator: undefined
  })
  to satisfy
  function (e) {
    hasAssertionErrorMessage(e, theMessage);
  }

  UnexpectedError: 
  expected [ 0 ] not to equal [ 0 ]
  
      at wrappedExpect (lib/assertTheUnexpected.js:109:28)
      at Function.notDeepStrictEqual (lib/assertTheUnexpected.js:438:7)
      at test/assertTheUnexpected.js:240:16
      at Context.&lt;anonymous&gt; (test/assertTheUnexpected.js:239:7)
      set UNEXPECTED_FULL_TRACE=true to see the full stack trace

  6) assertTheUnexpected notStrictEqual should respect a user supplied message:
     
expected
function () {
  assert.notStrictEqual(0, 0, theMessage);
}
to error
function (e) {
  hasAssertionErrorMessage(e, theMessage);
}
  expected
  AssertionError [ERR_ASSERTION]({
    message: 'oh dear', generatedMessage: false, code: 'ERR_ASSERTION',
    actual: undefined, expected: undefined, operator: undefined
  })
  to satisfy
  function (e) {
    hasAssertionErrorMessage(e, theMessage);
  }

  UnexpectedError: 
  expected 0 not to be 0
  
      at wrappedExpect (lib/assertTheUnexpected.js:109:28)
      at Function.notStrictEqual (lib/assertTheUnexpected.js:443:7)
      at test/assertTheUnexpected.js:252:16
      at Context.&lt;anonymous&gt; (test/assertTheUnexpected.js:251:7)
      set UNEXPECTED_FULL_TRACE=true to see the full stack trace

  7) assertTheUnexpected ok should respect a user supplied message:
     
expected function () { assert.ok(false, theMessage); } to error
function (e) {
  hasAssertionErrorMessage(e, theMessage);
}
  expected
  AssertionError [ERR_ASSERTION]({
    message: 'oh dear', generatedMessage: false, code: 'ERR_ASSERTION',
    actual: undefined, expected: undefined, operator: undefined
  })
  to satisfy
  function (e) {
    hasAssertionErrorMessage(e, theMessage);
  }

  UnexpectedError: 
  expected false to be truthy
  
      at wrappedExpect (lib/assertTheUnexpected.js:109:28)
      at checkTruthy (lib/assertTheUnexpected.js:303:5)
      at Function.ok (lib/assertTheUnexpected.js:446:7)
      at test/assertTheUnexpected.js:270:16
      at Context.&lt;anonymous&gt; (test/assertTheUnexpected.js:269:7)
      set UNEXPECTED_FULL_TRACE=true to see the full stack trace

  8) assertTheUnexpected strictEqual should respect a user supplied message:
     
expected
function () {
  assert.strictEqual('boo', 'hoo', theMessage);
}
to error
function (e) {
  hasAssertionErrorMessage(e, theMessage);
}
  expected
  AssertionError [ERR_ASSERTION]({
    message: 'oh dear', generatedMessage: false, code: 'ERR_ASSERTION',
    actual: undefined, expected: undefined, operator: undefined
  })
  to satisfy
  function (e) {
    hasAssertionErrorMessage(e, theMessage);
  }

  UnexpectedError: 
  expected 'boo' to be 'hoo'
  
  -boo
  +hoo
  
      at wrappedExpect (lib/assertTheUnexpected.js:109:28)
      at Function.strictEqual (lib/assertTheUnexpected.js:451:7)
      at test/assertTheUnexpected.js:282:16
      at Context.&lt;anonymous&gt; (test/assertTheUnexpected.js:281:7)
      set UNEXPECTED_FULL_TRACE=true to see the full stack trace

  9) assertTheUnexpected throws should pass on seeing an exception:
     
expected
function () {
  assert.throws(function () { throw new Error('boo'); });
}
not to error
  threw: AssertionError [ERR_ASSERTION]({
    message: 'Missing expected exception..', generatedMessage: false,
    code: 'ERR_ASSERTION', actual: undefined, expected: undefined,
    operator: undefined
  })

  Error: boo
      at test/assertTheUnexpected.js:292:43
      at lib/assertTheUnexpected.js:269:9
      at checkThrows (lib/assertTheUnexpected.js:268:7)
      at Function.throws (lib/assertTheUnexpected.js:454:7)
      at test/assertTheUnexpected.js:292:16
      at Context.&lt;anonymous&gt; (test/assertTheUnexpected.js:291:7)
      set UNEXPECTED_FULL_TRACE=true to see the full stack trace

  10) assertTheUnexpected when used a plain function should respect a user supplied message:
     
expected function () { assert.ok(false, theMessage); } to error
function (e) {
  hasAssertionErrorMessage(e, theMessage);
}
  expected
  AssertionError [ERR_ASSERTION]({
    message: 'oh dear', generatedMessage: false, code: 'ERR_ASSERTION',
    actual: undefined, expected: undefined, operator: undefined
  })
  to satisfy
  function (e) {
    hasAssertionErrorMessage(e, theMessage);
  }

  UnexpectedError: 
  expected false to be truthy
  
      at wrappedExpect (lib/assertTheUnexpected.js:109:28)
      at checkTruthy (lib/assertTheUnexpected.js:303:5)
      at Function.ok (lib/assertTheUnexpected.js:446:7)
      at test/assertTheUnexpected.js:346:16
      at Context.&lt;anonymous&gt; (test/assertTheUnexpected.js:345:7)
      set UNEXPECTED_FULL_TRACE=true to see the full stack trace




    at createError (/home/travis/build/alexjeffburke/unexpected-build-canary/node_modules/fugl/src/run-in-folder.js:17:10)
    at ChildProcess.npm.on.code (/home/travis/build/alexjeffburke/unexpected-build-canary/node_modules/fugl/src/run-in-folder.js:58:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)</pre><pre style="display: none;"><code></code></pre></li><li class="test pass slow"><h2>jest-unexpected<span class="duration">63973ms</span> <a href="blank?grep=jest-unexpected" class="replay">‣</a></h2><pre style="display: none;"><code></code></pre></li><li class="test pass slow"><h2>unchecked<span class="duration">32421ms</span> <a href="blank?grep=unchecked" class="replay">‣</a></h2><pre style="display: none;"><code></code></pre></li><li class="test pass slow"><h2>graphql-client-benchmarks<span class="duration">37429ms</span> <a href="blank?grep=graphql-client-benchmarks" class="replay">‣</a></h2><pre style="display: none;"><code></code></pre></li><li class="test pass slow"><h2>confer-js<span class="duration">12951ms</span> <a href="blank?grep=confer-js" class="replay">‣</a></h2><pre style="display: none;"><code></code></pre></li><li class="test pass slow"><h2>browser-resolve-cli<span class="duration">36276ms</span> <a href="blank?grep=browser-resolve-cli" class="replay">‣</a></h2><pre style="display: none;"><code></code></pre></li></ul></div>
  

</body></html>